baseURL = "https://blog.bing0ne.com"
languageCode = "en"
title = "bing0ne Base"
theme = "paper"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
enableEmoji = true
hasCJKLanguage = true
preserveTaxonomyNames = true

# Disqus Username
disqusShortname = "bing0ne"

# Google Analytics UA number
googleAnalytics = "UA-71832126-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Dev"
  weight = 20
  identifier = "dev"
  url = "/categories/dev/"

[[menu.main]]
  name = "Eassy"
  weight = 30
  identifier = "eassy"
  url = "/categories/eassy/"

[[menu.main]]
  name = "GSoC"
  weight = 40
  identifier = "gsoc"
  url = "/categories/gsoc/"

[[menu.main]]
  name = "Tags"
  weight = 50
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Bingwen Ma"
  # bg = "images/grey-prism.svg"
  avatar = "img/avatar-bing0ne.jpeg"
  seotitle = "bing0ne Base"
  subtitle = "~ Keep It Simple & Stupid ~"
  description = "bing0ne Base"
  paginate = 10

  # Choose your social networks
  email = "hi@bing0ne.com"
  github = "bing0n3"
  twitter = "bing0ne"
  # linkedin = "bing0ne"
  # weibo = "ponymbw"
  # wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  # stackoverflow = "laozhu"
  # codesandbox = "melaozhu"
  # npm = "laozhu"
  # reddit = "melaozhu"

  # Overrid theme styles in this file
  customStyle = "styles/custom.scss"

  # Changyan Comments (China Only)
  changyan = false
  changyanId = "cyt3toRiB"
  changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

[permalinks]
  post = "/p/:slug"
