baseURL = "https://blog.bing0ne.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "bing0ne Base"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = "UA-71832126-1"                 # your google analytics id
disqusShortname = "bing0ne"                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "bing0ne"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
#[[menu.main]]
#  name = "About"
#  weight = 40
#  identifier = "about"
#  url = "/about/"

[params]
  subTitle = "Neverland"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "Share Memory by Communication"                                          # site's footer slogan  # 网站页脚标语
  keywords = ["blog", "bing0ne","gopher", "gsoc"]                                  # site's keywords  # 网站关键字
  description = "bing0ne Knowledge Base"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  twitter = "https://twitter.com/bing0n3"
  #facebook = " "
  #weibo = " "
  instagram = "https://instagram.com/bing0n3"
  github = "https://github.com/bing0n3"


[permalinks]
  post = "/p/:slug"